# Generated by Django 5.1.1 on 2024-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=23)),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=29)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_no', models.CharField(max_length=10)),
                ('supplier', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
