# Generated by Django 5.0.7 on 2024-12-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryQuantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
