# Generated by Django 5.0.7 on 2024-12-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('individual_items', models.ManyToManyField(blank=True, related_name='project_item_item_code', to='inventory.individualitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_item', to='inventory.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_item_project', to='inventory.project')),
            ],
        ),
    ]
