# Generated by Django 5.0.7 on 2024-11-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemQuantity',
        ),
        migrations.AlterField(
            model_name='item',
            name='itemCode',
            field=models.CharField(editable=False, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=30),
        ),
    ]
