# Generated by Django 5.1.1 on 2024-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=23)),
                ('no_of_items_in_category', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Inventory',
            new_name='Items',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='item',
            new_name='item_name',
        ),
    ]
