# Generated by Django 5.0.7 on 2024-12-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_categoryquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='price',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='quantity',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
