# Generated by Django 5.0.7 on 2024-12-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_projectitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='items',
        ),
    ]
