# Generated by Django 5.0.7 on 2024-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_itemquantity_alter_item_itemcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemQuantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
