# Generated by Django 5.0.7 on 2024-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_itemquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code_index',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
