# Generated by Django 5.0.7 on 2024-12-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_project_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='individual_items',
            field=models.ManyToManyField(related_name='project_item_item_code', to='inventory.individualitem'),
        ),
    ]
