# Generated by Django 5.0.7 on 2024-12-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_projectitem_individual_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectitem',
            old_name='project',
            new_name='associated_project',
        ),
    ]
