# Generated by Django 5.0.7 on 2024-11-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_code_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='code_index',
        ),
    ]
