# Generated by Django 5.0.7 on 2024-11-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_item_code_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itemCode',
        ),
        migrations.CreateModel(
            name='IndividualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemCode', models.CharField(max_length=6, unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_items', to='inventory.item')),
            ],
        ),
    ]
