# Generated by Django 5.0.7 on 2024-12-09 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_transactionitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_category', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplieritem_item', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplieritem_supplier', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_supplier', to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactionitem_category', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactionitem_item', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionitem_transaction', to='inventory.transaction'),
        ),
    ]
