# Generated by Django 5.0.7 on 2024-12-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_transaction_paymentstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='paymentState',
            new_name='paymentStatus',
        ),
    ]
