# Generated by Django 5.0.7 on 2024-12-01 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_transaction_paymentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_items', to='inventory.transaction'),
        ),
    ]
